### ISSUE TITLE
Will DRAM-v also work on non-phage viruses like NCLDV? 

### ISSUE THREAD

**Issue by casett** [WrightonLabCSU/DRAM#234]
I am using DRAM-v in some work profiling viral communities that are largely comprised of dsDNA phage but also have some NCLDV in them. I am wondering if DRAM-v can handle eukaryotic viral AMG predictions or if it was only intended for use in conjunction with bacteria/archaea phage? Thanks

**Comment by jrr-microbio** [comment]
Hi Casett,

Thanks for using DRAM-v! 

We see no reason why DRAM would not be able to process and annotate genes found in NCLDVs. Keep in mind, though, that since DRAM uses reference databases that this will likely result in a lack of annotations since often times these databases are centered around bacteriophages. If the NCLDVs were predicted using VirSorter, once you add in the affi_tab files then you should get a normal output with the AMGs "scored" based on the metrics listed in the publication. If they were identified with other software/methods, then you will not get any AMG Scores or distillate, but you should be able to run it regardless and get the annotations. If you have a mix of VirSorter and non-VirSorter called vMAGs, I would recommend splitting them up and annotating them separately i.e., applying the affi_tab files when possible
