### ISSUE TITLE
DRAM running time

### ISSUE THREAD

**Issue by pabloati** [WrightonLabCSU/DRAM#310]
Hi,

I have been running DRAM on some small assembled genomes (2Megabytes) and the computing time when using Uniref is getting really high. It has already been running for more than 24 hours on a cluster with 30 CPUs and 250Gb of RAM memory. 

Is this normal, how long should I expect DRAM to be running when using UniRef to annotate?

Thank you

**Comment by rmFlynn** [comment]
This is at this point normal, if you can avoid using Unref I suggest you do so, it has a limited effect on the distillate.

**Comment by rmFlynn** [comment]
Seeing as this is expected behavior, I will close this ticket for now.

**Comment by asierFernandezP** [comment]
Hi! I am facing the same problem, with UniRef annotation not being able to finish (up to 6 days running, with only 100 viral contigs used as input). Is this still "the expected behaviour"? How much time would this require? And, can you provide additional information on how did you check that Uniref "has a limited effect on the distillate"? I would expect this database to provide the most information to the annotation process.

Thank you
