### ISSUE TITLE
DRAM-v uniref userwarning exit

### ISSUE THREAD

**Issue by y-hwang** [WrightonLabCSU/DRAM#48]
Hello, 

I am using DRAM-v annotate with --use_uniref flag and I get the following warning followed by an automatic exit.  

 UserWarning: No descriptions were found for your id's. Does this UniRef90_UPI0003FEEF98 look like an id from uniref_description

uniref90 seems to be set up properly on my config. How do I fix this error? thanks!

**Comment by mw55309** [comment]
You can open your description db. It should be in the DRAM_data directory

Try

```sh
sqlite3 description_db.sqlite
```

You should see:

```
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite>
```

You can then try:

```
select * from uniref_description where id = "UniRef90_UPI0003FEEF98
```

I just checked and I don't have that ID in my database

**Comment by mw55309** [comment]
In fact, I cannot find that ID even by searching Uniprot: https://www.uniprot.org/uniprot/?query=UniRef90_UPI0003FEEF98&sort=score

**Comment by shafferm** [comment]
Thanks for looking into this @mw55309.

It looks like I can see that identifier in UniParc: https://www.uniprot.org/uniparc/UPI0003FEEF98?sort=score. I'm not sure if it was previously in UniRef. @y-hwang have you changed out or updated the uniref90 or other uniprot resource you were using since your initial setup?

**Comment by rmFlynn** [comment]
This old uniref version problem will probably not be relevant to future users.
