### ISSUE TITLE
Set up databases in one directory in server  and want to use them in another directory/new session

### ISSUE THREAD

**Issue by nuriaher** [WrightonLabCSU/DRAM#81]
Hi, thanks in advanced.
I am trying to run DRAM in a server and the databases had to be set up in a shared directory by another user because of the size of these. I want to use DRAM in a new session from my directory but I can't specify the directory where the databases are and it appears as if these were never downloaded. Which is the path DRAM looks for the databses in? Can I do something to add that manually?

This is my command and error:
```
(base) [nurher]$ DRAM.py annotate -i path/in/server/assembly.fa -o annotation
1 fastas found
2021-05-06 09:47:49.610096: Annotation started
Traceback (most recent call last):
  File "/services/tools/dram/1.2.0/bin/DRAM.py", line 153, in <module>
    args.func(**args_dict)
  File "/services/tools/dram/1.2.0/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 967, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/services/tools/dram/1.2.0/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1000, in annotate_bins
    db_handler = DatabaseHandler(db_locs['description_db'])
  File "/services/tools/dram/1.2.0/lib/python3.9/site-packages/mag_annotator/database_handler.py", line 17, in __init__
    raise ValueError('Database does not exist at path %s' % database_loc)
ValueError: Database does not exist at path None
```

Thanks again,
Núria

**Comment by shafferm** [comment]
Hi Núria!

It seems like your DRAM install isn't finding the databases. When you run `DRAM-setup.py print_config` do you see a lot of Nones? Because the databases were set up by another user you will need to get your config set up. You can do this two different ways.

I think the easier way is to ask that other user to export the config that was generated as part of processing the databases. The command to do this is `DRAM-setup.py export_config --output_file DRAM_config` then they can share that `DRAM_config` file with you and you can import it to your DRAM setup using `DRAM-setup.py import_config --config_loc DRAM_config`.

The alternative is to using the `DRAM-setup.py set_database_locations` and set all of the locations manually. This is tedious but will also work.

Hope this helps!

Mike

**Comment by nuriaher** [comment]
Hi Mike,

Great, very helpful.

Thank you very much.

Núria
